# dbt_project.yml

# Name your project! 
name: 'dbt_ecommerce_project'
version: '1.0.0'

# Profile must match the name in your profiles.yml
profile: 'dbt_project' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# =======================================================
# MODEL CONFIGURATION (Bronze, Silver, Gold Layers)
# =======================================================
models:
  dbt_ecommerce_project:
    
    # ---------------------------------------------------
    # 1. BRONZE LAYER (Sources Only - No dbt Models)
    #
    #   * Goal: Represent raw data tables in a dedicated schema.
    #   * Action: Use the 'sources.yml' file to define them in schema 'bronze'.
    # ---------------------------------------------------
    
    # ---------------------------------------------------
    # 2. SILVER LAYER (Staging/Cleaned Models)
    #
    #   * Location: models/staging/
    #   * Goal: Clean, standardize, and select source data.
    #   * Strategy: Materialize as views for low latency and no storage duplication.
    # ---------------------------------------------------
    staging:
      # All models in models/staging/ will go to the 'silver' schema
      +schema: 'silver'
      # Materialize as views (fastest to run, always fresh, minimal cost)
      +materialized: view

    # ---------------------------------------------------
    # 3. GOLD LAYER (Mart/Business Models)
    #
    #   * Location: models/marts/
    #   * Goal: Final aggregations, business metrics (facts and dims).
    #   * Strategy: Materialize as tables for performance and cost control.
    # ---------------------------------------------------
    marts:
      # All models in models/marts/ will go to the 'gold' schema
      +schema: 'gold'
      # Materialize as tables (best for querying, but slower build time)
      +materialized: table
      
      # Optional: You can create sub-folders here for specific marts
      # dim:
      #   +materialized: table
      # fact:
      #   +materialized: table

# =======================================================
# SOURCE CONFIGURATION (BRONZE LAYER)
# =======================================================
# NOTE: This configuration does NOT go into dbt_project.yml.
# It should be placed in a separate file, typically `models/sources.yml`.
# This tells dbt where to find your raw (BRONZE) tables.
#